"""Esquemas ref (datos del banco), ops (linaje del ETL) y app (estado de la aplicación).

Generada con autogenerate desde backend/persistence/models.py y revisada a mano: se agregan
la creación de esquemas y la vista app.card_status_effective.

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 16:47:40.464112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    for schema in ("ref", "ops", "app"):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 del session_token; el token no se guarda.'),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True, comment='Referencia lógica a ref.customers (sin FK). Nulo para role=agent.'),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role = 'agent' OR customer_id IS NOT NULL", name=op.f('ck_sessions_customer_required')),
    sa.CheckConstraint("role IN ('customer', 'agent')", name=op.f('ck_sessions_role')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash')),
    schema='app'
    )
    op.create_table('etl_runs',
    sa.Column('run_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('git_dirty', sa.Boolean(), nullable=True),
    sa.Column('source_dir', sa.Text(), nullable=True),
    sa.Column('duckdb_path', sa.Text(), nullable=True),
    sa.Column('duckdb_sha256', sa.String(length=64), nullable=True),
    sa.Column('data_as_of', sa.Date(), nullable=True, comment='Máximo process_date cargado en ref.transactions.'),
    sa.Column('customer_scope', sa.String(length=20), server_default='all', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Filas por tabla en cada capa: csv, raw, clean (DuckDB), ref (PostgreSQL), rejected.'),
    sa.Column('partitions_replaced', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("mode IN ('full', 'incremental')", name=op.f('ck_etl_runs_mode')),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'noop')", name=op.f('ck_etl_runs_status')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_etl_runs')),
    schema='ops'
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('customer_status', sa.String(length=20), nullable=False),
    sa.Column('detected_accent', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('etl_run_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers')),
    schema='ref',
    comment='Clientes. Solo las columnas que usa la app: sin documento, contacto, dirección, credit_score ni ingresos (docs/data/inventory.md).'
    )
    op.create_table('daily_exchange_rates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('buy_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('sell_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('etl_run_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'source_currency', 'target_currency', name='pk_daily_exchange_rates'),
    schema='ref'
    )
    op.create_table('rejected_rows',
    sa.Column('rejected_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('etl_run_id', sa.BigInteger(), nullable=False),
    sa.Column('table_name', sa.String(length=40), nullable=False),
    sa.Column('pk_value', sa.Text(), nullable=True),
    sa.Column('partition_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rejected_id', name=op.f('pk_rejected_rows')),
    schema='ref',
    comment='Cuarentena: filas que no cumplen integridad (FK, dueño del producto, partición). Nunca se borran en silencio.'
    )
    op.create_index('ix_rejected_rows_table_name_reason', 'rejected_rows', ['table_name', 'reason'], unique=False, schema='ref')
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('clarification_round', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('clarification_round BETWEEN 0 AND 3', name=op.f('ck_conversations_clarification_round')),
    sa.ForeignKeyConstraint(['session_id'], ['app.sessions.session_id'], name=op.f('fk_conversations_session_id_sessions')),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversations')),
    schema='app'
    )
    op.create_index('ix_conversations_customer_id_created_at', 'conversations', ['customer_id', 'created_at'], unique=False, schema='app')
    op.create_table('idempotency_keys',
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['app.sessions.session_id'], name=op.f('fk_idempotency_keys_session_id_sessions')),
    sa.PrimaryKeyConstraint('session_id', 'idempotency_key', name='pk_idempotency_keys'),
    schema='app'
    )
    op.create_index('ix_idempotency_keys_expires_at', 'idempotency_keys', ['expires_at'], unique=False, schema='app')
    op.create_table('etl_files',
    sa.Column('file_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('table_name', sa.String(length=40), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('partition_date', sa.Date(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('rows', sa.BigInteger(), nullable=False),
    sa.Column('rejected_rows', sa.BigInteger(), server_default='0', nullable=False, comment='Líneas mal formadas del CSV (lector de DuckDB).'),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("action IN ('loaded', 'new', 'changed')", name=op.f('ck_etl_files_action')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.etl_runs.run_id'], name=op.f('fk_etl_files_run_id_etl_runs')),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_etl_files')),
    schema='ops'
    )
    op.create_index('ix_etl_files_run_id', 'etl_files', ['run_id'], unique=False, schema='ops')
    op.create_index('ix_etl_files_table_name_source_file', 'etl_files', ['table_name', 'source_file'], unique=False, schema='ops')
    op.create_table('demo_customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('scenario', sa.String(length=40), nullable=False),
    sa.Column('scenario_rank', sa.SmallInteger(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['ref.customers.customer_id'], name=op.f('fk_demo_customers_customer_id_customers')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_demo_customers')),
    schema='ref',
    comment='Clientes de demo elegidos de forma determinista (semilla fija) por escenario; alimenta /api/demo/customers.'
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_number', sa.String(length=30), nullable=False, comment='No es UNIQUE: el dataset trae 6 números repetidos en productos distintos.'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('opening_branch_id', sa.String(length=20), nullable=True),
    sa.Column('product_status', sa.String(length=20), nullable=False),
    sa.Column('opening_channel', sa.String(length=30), nullable=True),
    sa.Column('has_linked_app', sa.Boolean(), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=True),
    sa.Column('last_transaction_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('etl_run_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['ref.customers.customer_id'], name=op.f('fk_products_customer_id_customers')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products')),
    sa.UniqueConstraint('product_id', 'customer_id', name='uq_products_product_id_customer_id'),
    schema='ref'
    )
    op.create_index('ix_products_customer_id', 'products', ['customer_id'], unique=False, schema='ref')
    op.create_table('confirmation_tokens',
    sa.Column('token_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True, comment='Un solo uso: se marca al consumir; si ya tiene valor, invalid_confirmation.'),
    sa.CheckConstraint("action IN ('create_dispute_case', 'lock_card')", name=op.f('ck_confirmation_tokens_action')),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.conversation_id'], name=op.f('fk_confirmation_tokens_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['session_id'], ['app.sessions.session_id'], name=op.f('fk_confirmation_tokens_session_id_sessions')),
    sa.PrimaryKeyConstraint('token_id', name=op.f('pk_confirmation_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_confirmation_tokens_token_hash')),
    schema='app'
    )
    op.create_table('handoffs',
    sa.Column('handoff_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Objeto completo de docs/handoff-schema.md.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('alta', 'media')", name=op.f('ck_handoffs_priority')),
    sa.CheckConstraint("reason_code IN ('fuera_de_plazo', 'riesgo_alto', 'aclaracion_agotada', 'pide_humano', 'fallo_tool', 'accion_no_verificada', 'acceso_no_autorizado')", name=op.f('ck_handoffs_reason_code')),
    sa.CheckConstraint("status IN ('pendiente', 'tomado', 'cerrado')", name=op.f('ck_handoffs_status')),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.conversation_id'], name=op.f('fk_handoffs_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('handoff_id', name=op.f('pk_handoffs')),
    schema='app'
    )
    op.create_index('ix_handoffs_status_created_at', 'handoffs', ['status', 'created_at'], unique=False, schema='app')
    op.create_table('turns',
    sa.Column('turn_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('state_before', sa.String(length=40), nullable=True),
    sa.Column('state_after', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'assistant', 'system')", name=op.f('ck_turns_role')),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.conversation_id'], name=op.f('fk_turns_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('turn_id', name=op.f('pk_turns')),
    sa.UniqueConstraint('conversation_id', 'seq', name=op.f('uq_turns_conversation_id_seq')),
    schema='app'
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=30), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False, comment='Tal como viene (sin zona). Evidencia: siempre 6–30 h después de process_date → UTC con día hábil en UTC-6.'),
    sa.Column('process_date', sa.Date(), nullable=False, comment='Partición diaria y día hábil local; unidad de la carga incremental.'),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=True, comment='Original del dataset; nulo en USD.'),
    sa.Column('amount_usd_filled', sa.Numeric(precision=15, scale=2), nullable=True, comment='amount_usd o amount × tasa diaria (ASOF); igual a amount en USD.'),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('branch_id', sa.String(length=20), nullable=True),
    sa.Column('merchant_name', sa.String(length=150), nullable=True),
    sa.Column('merchant_category', sa.String(length=50), nullable=True),
    sa.Column('transaction_country', sa.String(length=50), nullable=False),
    sa.Column('transaction_city', sa.String(length=100), nullable=True),
    sa.Column('transaction_status', sa.String(length=20), nullable=False),
    sa.Column('response_code', sa.String(length=10), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('etl_run_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['ref.customers.customer_id'], name='fk_transactions_customer_id_customers'),
    sa.ForeignKeyConstraint(['product_id', 'customer_id'], ['ref.products.product_id', 'ref.products.customer_id'], name='fk_transactions_product_owner'),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transactions')),
    schema='ref'
    )
    op.create_index('ix_transactions_customer_id_amount', 'transactions', ['customer_id', 'amount'], unique=False, schema='ref')
    op.create_index('ix_transactions_customer_id_transaction_date', 'transactions', ['customer_id', sa.literal_column('transaction_date DESC')], unique=False, schema='ref')
    op.create_index('ix_transactions_process_date', 'transactions', ['process_date'], unique=False, schema='ref')
    op.create_index('ix_transactions_product_id', 'transactions', ['product_id'], unique=False, schema='ref')
    op.create_table('card_status_overrides',
    sa.Column('override_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.String(length=40), nullable=True),
    sa.Column('confirmation_token_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Blocked', 'Active')", name=op.f('ck_card_status_overrides_status')),
    sa.ForeignKeyConstraint(['confirmation_token_id'], ['app.confirmation_tokens.token_id'], name=op.f('fk_card_status_overrides_confirmation_token_id_confirmation_tokens')),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.conversation_id'], name=op.f('fk_card_status_overrides_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('override_id', name=op.f('pk_card_status_overrides')),
    sa.UniqueConstraint('confirmation_token_id', name=op.f('uq_card_status_overrides_confirmation_token_id')),
    schema='app',
    comment='Bloqueos de tarjeta hechos por la app. Estado efectivo = override más reciente o ref.products.product_status.'
    )
    op.create_index('ix_card_status_overrides_product_id_created_at', 'card_status_overrides', ['product_id', sa.literal_column('created_at DESC')], unique=False, schema='app')
    op.create_table('dispute_cases',
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=30), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=True),
    sa.Column('turn_id', sa.String(length=40), nullable=True),
    sa.Column('confirmation_token_id', sa.String(length=40), nullable=True, comment='UNIQUE: el mismo token no crea dos reclamos (escritura idempotente por token).'),
    sa.Column('status', sa.String(length=20), server_default='registrado', nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('customer_statement', sa.Text(), nullable=True),
    sa.Column('policy_rules_applied', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('registrado', 'en_revision', 'resuelto', 'rechazado', 'anulado')", name=op.f('ck_dispute_cases_status')),
    sa.ForeignKeyConstraint(['confirmation_token_id'], ['app.confirmation_tokens.token_id'], name=op.f('fk_dispute_cases_confirmation_token_id_confirmation_tokens')),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.conversation_id'], name=op.f('fk_dispute_cases_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['turn_id'], ['app.turns.turn_id'], name=op.f('fk_dispute_cases_turn_id_turns')),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_dispute_cases')),
    sa.UniqueConstraint('confirmation_token_id', name=op.f('uq_dispute_cases_confirmation_token_id')),
    schema='app'
    )
    op.create_index('ix_dispute_cases_status_created_at', 'dispute_cases', ['status', 'created_at'], unique=False, schema='app')
    op.create_index('uq_dispute_cases_open_customer_transaction', 'dispute_cases', ['customer_id', 'transaction_id'], unique=True, schema='app', postgresql_where=sa.text("status IN ('registrado', 'en_revision')"))
    op.create_table('traces',
    sa.Column('trace_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('turn_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('tool', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Entradas y salidas (enmascaradas), reglas evaluadas. Sin cadena de pensamiento.'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('llm', 'tool', 'policy', 'controller')", name=op.f('ck_traces_kind')),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.conversation_id'], name=op.f('fk_traces_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['turn_id'], ['app.turns.turn_id'], name=op.f('fk_traces_turn_id_turns')),
    sa.PrimaryKeyConstraint('trace_id', name=op.f('pk_traces')),
    sa.UniqueConstraint('turn_id', 'step_seq', name=op.f('uq_traces_turn_id_step_seq')),
    schema='app'
    )
    # Estado efectivo de una tarjeta: el override más reciente de la app o, si no hay, el de ref.products.
    # La recarga de ref (TRUNCATE + COPY) no toca los overrides.
    op.execute("""
        CREATE VIEW app.card_status_effective AS
        SELECT p.product_id, p.customer_id, p.product_type,
               COALESCE(o.status, p.product_status) AS status,
               p.product_status AS ref_status, o.created_at AS overridden_at, o.override_id
        FROM ref.products p
        LEFT JOIN LATERAL (
            SELECT status, created_at, override_id FROM app.card_status_overrides c
            WHERE c.product_id = p.product_id AND c.customer_id = p.customer_id
            ORDER BY created_at DESC, override_id DESC LIMIT 1) o ON TRUE""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS app.card_status_effective")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traces', schema='app')
    op.drop_index('uq_dispute_cases_open_customer_transaction', table_name='dispute_cases', schema='app', postgresql_where=sa.text("status IN ('registrado', 'en_revision')"))
    op.drop_index('ix_dispute_cases_status_created_at', table_name='dispute_cases', schema='app')
    op.drop_table('dispute_cases', schema='app')
    op.drop_index('ix_card_status_overrides_product_id_created_at', table_name='card_status_overrides', schema='app')
    op.drop_table('card_status_overrides', schema='app')
    op.drop_index('ix_transactions_product_id', table_name='transactions', schema='ref')
    op.drop_index('ix_transactions_process_date', table_name='transactions', schema='ref')
    op.drop_index('ix_transactions_customer_id_transaction_date', table_name='transactions', schema='ref')
    op.drop_index('ix_transactions_customer_id_amount', table_name='transactions', schema='ref')
    op.drop_table('transactions', schema='ref')
    op.drop_table('turns', schema='app')
    op.drop_index('ix_handoffs_status_created_at', table_name='handoffs', schema='app')
    op.drop_table('handoffs', schema='app')
    op.drop_table('confirmation_tokens', schema='app')
    op.drop_index('ix_products_customer_id', table_name='products', schema='ref')
    op.drop_table('products', schema='ref')
    op.drop_table('demo_customers', schema='ref')
    op.drop_index('ix_etl_files_table_name_source_file', table_name='etl_files', schema='ops')
    op.drop_index('ix_etl_files_run_id', table_name='etl_files', schema='ops')
    op.drop_table('etl_files', schema='ops')
    op.drop_index('ix_idempotency_keys_expires_at', table_name='idempotency_keys', schema='app')
    op.drop_table('idempotency_keys', schema='app')
    op.drop_index('ix_conversations_customer_id_created_at', table_name='conversations', schema='app')
    op.drop_table('conversations', schema='app')
    op.drop_index('ix_rejected_rows_table_name_reason', table_name='rejected_rows', schema='ref')
    op.drop_table('rejected_rows', schema='ref')
    op.drop_table('daily_exchange_rates', schema='ref')
    op.drop_table('customers', schema='ref')
    op.drop_table('etl_runs', schema='ops')
    op.drop_table('sessions', schema='app')
    for schema in ("app", "ops", "ref"):
        op.execute(f"DROP SCHEMA IF EXISTS {schema}")
    # ### end Alembic commands ###
